[plantuml, format="png", id="user_oshpd"]
----
actor user_oshpd [
  <b>OSHPD User
]
----

[plantuml, format="png", id="user_public"]
----
actor user_public [
  <b>Public User
]
----

[plantuml, format="png", id="user_anonymous"]
----
actor user_anonymous [
  <b>Anonymous User
]
----
