@startuml (id="user_oshpd")
actor user_oshpd [
  <b>OSHPD User
]
@enduml

@startuml (id="user_public")
actor user_public [
  <b>Public User
]
@enduml

@startuml (id="user_anonymous")
actor user_anonymous [
  <b>Anonymous User
]
@enduml
